### ISSUE TITLE
Playlist under edit cannot be refreshed after all the track matches were found 

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#219] opened 2023-10-08 11:44 UTC
**listFix() v2.9.0**

**Steps:**

1. Open a playlist for editing in the editor. The playlist should contain a mix of OK tracks (already matched tracks), plus Exclamation-marked tracks (those tracks for which matches are still to be found):

2. Activate the repair (magic wand) on the playlist.

3. Once the all the appropriate matches have been found, close the last processing dialogue, i.e. "Select closest matches" by pressing the cancel button to return to the playlist.

3. Issue upon return to the playlist: **the playlist cannot be refreshed**. The refresh button is unavailable/dulled. To refresh the playlist, it has to be closed first, and then reopened.

**Comment by Borewit** [comment] 2023-10-21 10:10
I cannot reproduce this behavior. It did however came across some code inconsistencies, which I addressed in PR #222.

Can you retest with the build of PR #218 (maybe this is the version you currently have installed)?

**Comment by Borewit** [comment] 2023-10-21 10:24
Duplicate of #195?

**Comment by touwys** [comment] 2023-10-22 12:00
> Duplicate of #195?

Same process, but slightly different approach. I think it's safe to combine the two (#195 & #219) as one issue. That said, strangely, I am now also unable to reproduce #219 (using build 2.9.0-1_edf148f). Would you rather combine the two issues into one, so that we can observe its impact on operations?

I am also going to add a note at #195 for additional information.

**Comment by Borewit** [comment] 2023-10-22 12:17
Closing this issue as it can no longer be reproduced on a recent build, #218 may have resolved it.

**Closed as completed by Borewit** 2023-10-22 12:17 UTC
Labels: Could not be reproduced
