### ISSUE TITLE
adding a playlist 

### ISSUE THREAD

**Issue by Freedom16789** [Borewit/listFix#265] opened 2024-05-13 12:37 UTC
Keep getting the error when i add a play list  the play list was working with the program be for. 

There was a problem opening the file you selected, are you sure it was a playlist?java.io.IOException: Failed to read playlist using provider-id=wpl: "C:\Users\Freedom16789\Music\Music\Playlists\Anime Sound Tracks.wpl"at io.github.borewit.lizzy.playlist.SpecificPlaylistFactory.readFrom(null:-1)at listfix.io.playlists.LizzyPlaylistUtil.readPlaylist(null:-1)at listfix.model.playlists.Playlist.load(null:-1)at listfix.model.playlists.PlaylistFactory.getPlaylist(null:-1)at listfix.view.GUIScreen$10.doInBackground(null:-1)at listfix.view.GUIScreen$10.doInBackground(null:-1)at javax.swing.SwingWorker$1.call(null:-1)at java.util.concurrent.FutureTask.run(null:-1)at javax.swing.SwingWorker.run(null:-1)at java.util.concurrent.ThreadPoolExecutor.runWorker(null:-1)at java.util.concurrent.ThreadPoolExecutor$Worker.run(null:-1)at java.lang.Thread.run(null:-1)

**Comment by Borewit** [comment] 2024-06-08 09:18
Duplicate of #264.

You can add additional comments to existing issues. Only one issue for one problem shall be opened.

**Closed as completed by Borewit** 2024-06-08 09:18 UTC
