### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by Borewit** [Borewit/listFix#64] opened 2023-02-06 15:46 UTC
This issue is to capture regressions tests.

**Comment by Borewit** [comment] 2023-02-06 15:48
_Copied from https://github.com/Borewit/listFix/pull/61#issuecomment-1419025370_

**listFix_2.5.1-[PR61]-10**

1. This build was installed straight away, skipping the other two.

2. The Playlist and Media Directories were added, anew.

3. Changed these programme options: font size and style, theme, and the number of closest matches to return when searches for. 

4. Selected 12 contiguous playlists from the playlist directory.

5. Opened all 12 playlists in the "Playlist Editor". 

_—— 5.1 In order to standardise, shall we consider to rather call the playlist repair pane the "Playlist Editor" from now on — or do you perhaps want to standardise on something else? In fact, I think this pane should get a title at the top? What do you think? Clear and precise naming is important for so many usage and support reasons._

_—— 5.2 The tab-titles of the all 12 playlists, now open in the "Playlist Editor", were corrupted as before (#55) — exhibiting what appears to be superimposed labels/text._

_—— 5.3 Each of the labels now displays the tab-closer "x" visibly, where it should. Clicking the "x", closes the tab properly._

_—— 5.4 A right mouse click, activates the tab, but nothing else happens. Is this action not supposed to evoke the tab context menu, which controls certain operations to be performed on it, such as:  close the tab, close all tabs, close other tabs, and more?_

_—— 5.5 The command to close all tabs, were only possible to execute from the File menu, as well as the keyboard shortcut CTRL+Shift+W._ 

_—— 5.6 After closing them all (5.5), one playlist remained behind in the "Playlist Editor" — but without its tab — and this playlist was impossible to close by any of the usual means. It only cleared after restarting the app.__ 

6. Next, tested one broken track found in a playlist. The closest match for it was quickly located, and displayed in the "Select Closest Matches" dialogue. The Preview>Play action worked as it should. However—

_—— 6.1 Clicking the "OK" button did not fix the broken track in the playlist._

The test ended at step 6. Awaiting response.

•
[Playlist Editor Status (19)](https://user-images.githubusercontent.com/65730626/216973218-c9a0fd53-0dbe-4352-90b8-ff6e27d268ca.png)
•
[Playlist Editor Status (53)](https://user-images.githubusercontent.com/65730626/216973313-6d3b3549-3348-4269-b95c-d57aa72dcac7.png)
•

**Comment by Borewit** [comment] 2023-02-06 15:50
Build of default branch, commit https://github.com/Borewit/listFix/commit/72f962748f5410004fea7390fe01b51d087e0275:  [listFix_2.5.1-8.exe](https://www.mediafire.com/file/yhjkiafcwy7zou3/listFix_2.5.1-8.exe/file)

**Comment by Borewit** [comment] 2023-02-08 19:42
Can you review this version @touwys? 

[listFix_2.5.1-18](https://www.mediafire.com/file/1a4bju1n6e0mxuf/listFix_2.5.1-18.exe/file)

Build of the default (main) branch. So this is how listFix() would like (except the version) if I would release it now.
In PR #72 (merged), I added additional exception handler which may log issues, which used to get lost.
Also I fixed a NullPointerException in one the repair functions.

This is your regression issue, feel to report in the way which it suits you best.

This video which explains issues (boxes) don't "touch" 😉: https://www.youtube.com/watch?v=29JPnJSmDs0

**Comment by Borewit** [comment] 2023-02-09 19:58
@touwys, does this [listFix_2.5.1-19](https://www.mediafire.com/file/ez3yydkdjwbzpqv/listFix_2.5.1-19.exe/file) fix #55?

**Comment by touwys** [comment] 2023-02-10 10:24
_> @touwys, does this [listFix_2.5.1-19](https://www.mediafire.com/file/ez3yydkdjwbzpqv/listFix_2.5.1-19.exe/file) fix #55?_

No, unfortunately, it did not. Sorry for the delay in reporting results — caused by ungovernable issues. 

Looking forward to the fix for this. :thumbsup:

•
[SCREENSHOT: listFix_2.5.1-19—Issue #55](https://user-images.githubusercontent.com/65730626/218063032-d3cbc1da-3363-4928-aecc-5fe8f26b4b7b.png)
•

> _his video which explains issues (boxes) don't "touch"_ 

Good show, thanks! My blank box appears to have replaced all the others. :joy:

**Comment by Borewit** [comment] 2023-02-11 11:28
> No, unfortunately, it did not. Sorry for the delay in reporting results — caused by ungovernable issues.

No worries, I am more then happy if you do it eventually. I read an [article in the New York Times](https://www.nytimes.com/2023/02/09/world/africa/south-africa-power-energy-crisis.html) about these black outs, what a tragedy.

I would love to nail this bug. No Exception stack-traces in the log file neither?

**Comment by touwys** [comment] 2023-02-11 14:59
> I would love to nail this bug. No Exception stack-traces in the log file neither?

Thanks, I really wish for you to find it soon.

There is now a log file added below, in which several _"NullPointerException"_ errors present. Are they related to this issue?

•
[rollingfile.log _ listFix_2.5.1-19](https://github.com/Borewit/listFix/files/10713917/listFix_2.5.1-19.exe._.rollingfile._.20230211_1633.log)
• 

Most of the log entries are from yesterday. Before posting the log, I quickly started listFix_2.5.1-19, and then, first thing, opened a number of playlist in the Playlist Editor, and then immediately, closed the app again. This was done just to create a current log entry.

**Comment by Borewit** [comment] 2023-02-11 19:07
Build [listFix_2.5.1-25.exe](https://www.mediafire.com/file/fpz37wdxuguekq6/listFix_2.5.1-25.exe/file), of https://github.com/Borewit/listFix/commit/35b55f08f51bfe05881cc4c593cbc23a1869e3dc

**Comment by touwys** [comment] 2023-02-11 19:11
> Build [listFix_2.5.1-25.exe](https://www.mediafire.com/file/fpz37wdxuguekq6/listFix_2.5.1-25.exe/file), of [35b55f0](https://github.com/Borewit/listFix/commit/35b55f08f51bfe05881cc4c593cbc23a1869e3dc)

Thanks, will test this build tomorrow. 👍

**Comment by touwys** [comment] 2023-02-12 07:53
**listFix_2.5.1-25**

1. Playlist Directory: Action — Open a playlist — The progress bar is now operational.
2. Playlists Editor: Playlist tabs: The double-printed tab-titles persist.

•

_Note on Item 1 above_ 

Can the colour intensity of the progress bar be intensified, slightly, for increased visibility?

**Comment by Borewit** [comment] 2023-02-12 11:13
> There is now a log file added below, in which several "NullPointerException" errors present. Are they related to this issue?

At least something tangible, see PR #89 in which I try to resolve that exception.

**Comment by Borewit** [comment] 2023-02-26 10:37
Copied from: https://github.com/Borewit/listFix/pull/114#issuecomment-1445319342

**Testing listFix_2.6.0-PR114-5**

**Steps:**

1. Un-installed listFix_2.6.0-[PR106]-5, including deleting "rollingfile.log" file, plus ".listFix()position.ini"

2. Install listFix_2.6.0-PR114-5, and continue with the initial set up of listFix.

3. Drag and drop playlist folders into PLD

ℹ️ _3.1 Not possible yet._

5. Add playlist folder to PLD via Windows Explore.

6. Add Media Directory.

7. Open and change 3 "Options", namely: Look & Feel, Font, Number of closest matches to return.

8. Open, and close immediately, several playlists in PLE.

9. Open 1 playlist in PLE to test various functions:

10. Select the 4 exclusively _unmatched_ tracks out of 12 tracks in total.

11. Click on the "Find Exact Matches" binoculars icon on the PLE toolbar.

ℹ️ _10.1 The progress dialogue is _not_ called up in display. That said, however, 3 out of 4 matches were found almost instantly. This progress dialogue probably need not be displayed if the action is completed so quickly? But, is that consistent to providing GUI progress information to the user?_

ℹ️ _10.2 How do we verify the accuracy of any exact matches found by the action, "Find Exact Matches"? The only test available to check how accurate the match it found is, is after the fact, i.e. _after_ the fix is already in? Of course, if the exact matches found are consistently, perfectly reliable, this is not essential as it is for finding closest matches._ 

12. Select the action: "Reload" to cancel the exact matches found, of Step 10.

13. Select the same 4 _unmatched_ tracks, _again_.

14. This time, call the action "Find Closest Matches" from the _context menu_ of the 4 selected, unmatched, tracks. The closest matches are found and in display. 

ℹ️ _13.1 This action calls an _unnamed_ progress bar, which in turn is followed by displaying the "Select Closest Matches" dialogue, containing the 4 matched tracks._

15. In the "Select Closest Matches" dialogue, call the action: Press Preview / PLAY for each track in turn: 

✔️ _14.1 Default media player now starts, and 4 out of 4 tracks are played back._

16. In the "Select Closest Matches" dialogue, right-click to call "Open File Location" of the best match.

❌ _15.1 There is no reaction. Thus, unavailable for further testing for the problem that was cited here: https://github.com/Borewit/listFix/pull/106#issuecomment-1443590093_

17. Click "Cancel" to close the "Select Closest Matches" dialogue.

18. Select "Fix Everything" magic wand in toolbar to repeat Step 12.

❓ _17.1 Calls first a "Repairing" progress dialogue, which is then followed by "Finding closest matches for all missing files" progress dialogue, which is, in turn, is finally followed by "Select Closest Matches". Is the first dialogue, "Repairing", really needed here? Its display seems to be redundant._

❓ _17.2 Should there not be consistency in the use of dialogues/operations/actions of Steps 15 & 17?

18. PLD > Right-click playlist folder > Context Menu: "Remove Playlist Directory" to remove a playlist folder from the PLD. 

✔️ _18.1 It cleared as expected._

• 
[rollingfile.log](https://github.com/Borewit/listFix/files/10833291/rollingfile.log)
•

**Closed as completed** 2023-10-03 17:03 UTC
